# field_coordinates.py
"""
מפת תיבות-תיחום (Bounding Boxes) לכל שדה על גבי form101_page1.jpg (2480x3508 פיקסלים).
זהו מקור האמת היחיד לקואורדינטות - הן pdf_service.py והן עורך הכיול (/calibrate) קוראים/
כותבים למבנה הזה.

מבנה לכל שדה:
{
    "x": int, "y": int,             # פינה שמאלית-עליונה של התיבה
    "width": int, "height": int,    # גודל התיבה - טקסט מתכווץ אוטומטית (Auto-Fit) כדי להיכנס
    "num_chars": int (אופציונלי),   # לשדות משבצות (ת.ז/תאריך) - כמה תווים לחלק ברוחב התיבה
    "step_x": int (אופציונלי)       # דריסה ידנית של המרווח בין משבצות, אם לא רוצים auto מ-num_chars
}
"""

DEFAULT_FIELD_COORDINATES = {
    "tax_year": {"x": 1250, "y": 255, "width": 220, "height": 55},
    "employer_name": {"x": 1560, "y": 505, "width": 500, "height": 45},
    "employer_tik_nikuyim": {"x": 35, "y": 505, "width": 240, "height": 45, "num_chars": 8},
    "tz": {"x": 1970, "y": 638, "width": 370, "height": 42, "num_chars": 9},
    "last_name": {"x": 1660, "y": 638, "width": 300, "height": 42},
    "first_name": {"x": 1125, "y": 638, "width": 510, "height": 42},
    "birth_date": {"x": 745, "y": 638, "width": 360, "height": 42, "num_chars": 6},
    "aliyah_date": {"x": 380, "y": 638, "width": 345, "height": 42, "num_chars": 6},
    "sex_male": {"x": 420, "y": 710, "width": 30, "height": 30},
    "sex_female": {"x": 245, "y": 710, "width": 30, "height": 30},
    "address_street": {"x": 1780, "y": 815, "width": 280, "height": 40},
    "address_city": {"x": 1470, "y": 810, "width": 280, "height": 40},
    "address_zip": {"x": 1160, "y": 800, "width": 280, "height": 40},
    "mobile": {"x": 900, "y": 740, "width": 280, "height": 40},
    "email": {"x": 20, "y": 740, "width": 450, "height": 40},
    "kupat_holim_name": {"x": 60, "y": 1045, "width": 300, "height": 40},
    "resident_yes": {"x": 637, "y": 950, "width": 30, "height": 30},
    "resident_no": {"x": 625, "y": 1005, "width": 30, "height": 30},
    "marital_married": {"x": 1047, "y": 950, "width": 30, "height": 30},
    "marital_single": {"x": 1243, "y": 992, "width": 30, "height": 30},
    "spouse_tz": {"x": 1970, "y": 1116, "width": 370, "height": 42, "num_chars": 9},
    "spouse_last_name": {"x": 1660, "y": 1116, "width": 300, "height": 42},
    "spouse_first_name": {"x": 860, "y": 1116, "width": 770, "height": 42},
    "spouse_birth_date": {"x": 480, "y": 1116, "width": 360, "height": 42, "num_chars": 6},
    "spouse_aliyah_date": {"x": 115, "y": 1116, "width": 350, "height": 42, "num_chars": 6},
    "spouse_income_none": {"x": 2107, "y": 1247, "width": 30, "height": 30},
    "spouse_income_has": {"x": 1313, "y": 1247, "width": 30, "height": 30},
    "child_name": {"x": 1950, "y": 1495, "width": 300, "height": 40},
    "child_tz": {"x": 1580, "y": 1495, "width": 350, "height": 40, "num_chars": 9},
    "child_dob": {"x": 1180, "y": 1495, "width": 280, "height": 40, "num_chars": 6},
    "child_row_height": {"x": 0, "y": 55, "width": 0, "height": 0},
    "no_other_income": {"x": 1010, "y": 1375, "width": 30, "height": 30},
    "other_income_salary": {"x": 1010, "y": 1525, "width": 30, "height": 30},
    "other_income_pension": {"x": 1010, "y": 1563, "width": 30, "height": 30},
    "other_income_allowance": {"x": 1010, "y": 1601, "width": 30, "height": 30},
    "other_income_partial": {"x": 1010, "y": 1639, "width": 30, "height": 30},
    "credit_here": {"x": 1010, "y": 1745, "width": 30, "height": 30},
    "credit_nothere": {"x": 1010, "y": 1825, "width": 30, "height": 30},
    "tax_coordination_approval": {"x": 850, "y": 1950, "width": 30, "height": 30},
    "credit_disabled_blind": {"x": 2280, "y": 2345, "width": 30, "height": 30},
    "credit_resident_locality": {"x": 2280, "y": 2455, "width": 30, "height": 30},
    "locality_name": {"x": 1900, "y": 2495, "width": 400, "height": 40},
    "credit_single_parent": {"x": 2280, "y": 2565, "width": 30, "height": 30},
    "credit_children_in_custody": {"x": 2280, "y": 2675, "width": 30, "height": 30},
    "credit_children_not_in_custody": {"x": 2280, "y": 2785, "width": 30, "height": 30},
    "credit_single_parent_toddlers": {"x": 2280, "y": 2895, "width": 30, "height": 30},
    "credit_children_disabled": {"x": 2280, "y": 3005, "width": 30, "height": 30},
    "credit_alimony_ex_spouse": {"x": 2280, "y": 3115, "width": 30, "height": 30},
    "credit_academic_degree": {"x": 2280, "y": 3225, "width": 30, "height": 30},
    "credit_reserve_duty": {"x": 2280, "y": 3335, "width": 30, "height": 30},
    "credit_new_immigrant": {"x": 2280, "y": 3445, "width": 30, "height": 30},
    "declared_true": {"x": 2280, "y": 3275, "width": 30, "height": 30},
    "signature": {"x": 350, "y": 3325, "width": 320, "height": 140},
}

FIELD_LABELS_FOR_EDITOR = [
    ("tax_year", "שנת המס", "א"),
    ("employer_name", "שם המעסיק", "א"),
    ("employer_tik_nikuyim", "מספר תיק ניכויים (אחרי ה-9)", "א"),
    ("tz", "ת.ז עובד/ת", "ב"),
    ("last_name", "שם משפחה", "ב"),
    ("first_name", "שם פרטי", "ב"),
    ("birth_date", "תאריך לידה", "ב"),
    ("aliyah_date", "תאריך עלייה", "ב"),
    ("sex_male", "תיבת סימון - זכר", "ב"),
    ("sex_female", "תיבת סימון - נקבה", "ב"),
    ("address_street", "רחוב ומספר", "ב"),
    ("address_city", "עיר/יישוב", "ב"),
    ("address_zip", "מיקוד", "ב"),
    ("mobile", "טלפון נייד", "ב"),
    ("email", "דוא\"ל", "ב"),
    ("kupat_holim_name", "שם קופת חולים", "ב"),
    ("resident_yes", "תיבת סימון - תושב ישראל: כן", "ב"),
    ("resident_no", "תיבת סימון - תושב ישראל: לא", "ב"),
    ("marital_married", "תיבת סימון - נשוי/ה", "ב"),
    ("marital_single", "תיבת סימון - רווק/ה", "ב"),
    ("spouse_tz", "ת.ז בן/בת זוג", "ג"),
    ("spouse_last_name", "שם משפחה - בן/בת זוג", "ג"),
    ("spouse_first_name", "שם פרטי - בן/בת זוג", "ג"),
    ("spouse_birth_date", "תאריך לידה - בן/בת זוג", "ג"),
    ("spouse_aliyah_date", "תאריך עלייה - בן/בת זוג", "ג"),
    ("spouse_income_none", "תיבת סימון - אין הכנסה לבן/בת זוג", "ג"),
    ("spouse_income_has", "תיבת סימון - יש הכנסה לבן/בת זוג", "ג"),
    ("child_name", "שם ילד/ה (שורה ראשונה)", "ד"),
    ("child_tz", "ת.ז ילד/ה (שורה ראשונה)", "ד"),
    ("child_dob", "תאריך לידה ילד/ה (שורה ראשונה)", "ד"),
    ("child_row_height", "מרווח אנכי בין שורות ילדים (Y בלבד)", "ד"),
    ("no_other_income", "תיבת סימון - אין הכנסות נוספות", "ה"),
    ("other_income_salary", "תיבת סימון - משכורת נוספת", "ה"),
    ("other_income_pension", "תיבת סימון - קצבה", "ה"),
    ("other_income_allowance", "תיבת סימון - מלגה", "ה"),
    ("other_income_partial", "תיבת סימון - משרה חלקית", "ה"),
    ("credit_here", "תיבת סימון - זיכוי כנגד הכנסה זו", "ו"),
    ("credit_nothere", "תיבת סימון - לא כנגד הכנסה זו", "ו"),
    ("tax_coordination_approval", "תיבת סימון - אישור תיאום מס מצורף", "ו"),
    ("credit_disabled_blind", "סעיף 1 - נכה/עיוור", "ז"),
    ("credit_resident_locality", "סעיף 2 - יישוב מזכה", "ז"),
    ("locality_name", "שם היישוב המזכה", "ז"),
    ("credit_single_parent", "סעיף 3 - הורה יחיד", "ז"),
    ("credit_children_in_custody", "סעיף 4 - ילדים בחזקה", "ז"),
    ("credit_children_not_in_custody", "סעיף 5 - ילדים שלא בחזקה", "ז"),
    ("credit_single_parent_toddlers", "סעיף 6 - הורה יחיד לפעוטות", "ז"),
    ("credit_children_disabled", "סעיף 8 - ילד עם מוגבלות", "ז"),
    ("credit_alimony_ex_spouse", "סעיף 9 - מזונות", "ז"),
    ("credit_academic_degree", "סעיף 10 - תואר אקדמי", "ז"),
    ("credit_reserve_duty", "סעיף 11 - מילואים", "ז"),
    ("credit_new_immigrant", "סעיף 12 - עולה חדש", "ז"),
    ("declared_true", "תיבת סימון - הצהרה", "ח"),
    ("signature", "תיבת החתימה (גודל = תיבת המקסימום)", "ח"),
]
